### ISSUE TITLE
Attributed 3.0 (And beyond) 

### ISSUE THREAD

**Issue by Nirma** [Nirma/Attributed#51]
## Intent of this issue
Keep track of what should be added and removed from Attributed and which improvements 
should be made to the existing API. 

## TODO
- [ ] Update the attributes of an existing attributed String
- [ ] Improve Support for applying attributes to ranges of a string
- [ ] Improve Documentation in README
- [ ] Increase code coverage past 70%

**Comment by Nirma** [comment]
@BasThomas  @vfn You did some great work before and I would love to get feedback on what you think should be improved.

**Comment by vfn** [comment]
@Nirma The todo list you have above is a great start. I'll add some more items if I can think of any.

**Comment by Nirma** [comment]
@vfn Thanks!

@karlvr I think I found your github! As you said I think we can shorten the method names!
